/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dynuclient;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.io.IOException;
import javax.swing.JOptionPane;

/**
 *
 * @author deneg
 */
public class DynuClientWindow extends javax.swing.JFrame {

    /**
     * Creates new form DynuClientWindow
     */
    private UpdateThread update=null;
    private Data data=null;
    
    public DynuClientWindow() {
        initComponents();
        Dimension dimension = Toolkit.getDefaultToolkit().getScreenSize();
        int x = (int) ((dimension.getWidth() - getWidth()) / 2);
        int y = (int) ((dimension.getHeight() - getHeight()) / 2);
        setLocation(x, y);
        this.data=Data.Load();
        this.txtUser.setText(this.data.User());
        this.txtPassword.setText(this.data.Password());
        this.txtTTL.setText(this.data.TTL());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lblUser = new javax.swing.JLabel();
        txtUser = new javax.swing.JTextField();
        lblPassword = new javax.swing.JLabel();
        txtPassword = new javax.swing.JTextField();
        btnStart = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtLog = new javax.swing.JTextArea();
        lblTTL = new javax.swing.JLabel();
        txtTTL = new javax.swing.JTextField();
        btnStop = new javax.swing.JButton();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Dynu Client");
        setBackground(new java.awt.Color(73, 77, 82));

        jPanel1.setBackground(new java.awt.Color(246, 246, 246));

        lblUser.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        lblUser.setForeground(new java.awt.Color(73, 77, 82));
        lblUser.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblUser.setText("User:");

        txtUser.setBackground(new java.awt.Color(246, 246, 246));
        txtUser.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        txtUser.setForeground(new java.awt.Color(73, 77, 82));
        txtUser.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        lblPassword.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        lblPassword.setForeground(new java.awt.Color(73, 77, 82));
        lblPassword.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPassword.setText("Password:");

        txtPassword.setBackground(new java.awt.Color(246, 246, 246));
        txtPassword.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        txtPassword.setForeground(new java.awt.Color(73, 77, 82));
        txtPassword.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        btnStart.setBackground(new java.awt.Color(168, 212, 252));
        btnStart.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        btnStart.setForeground(new java.awt.Color(73, 77, 82));
        btnStart.setText("Start");
        btnStart.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnStart.setBorderPainted(false);
        btnStart.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStartActionPerformed(evt);
            }
        });

        txtLog.setBackground(new java.awt.Color(246, 246, 246));
        txtLog.setColumns(20);
        txtLog.setForeground(new java.awt.Color(73, 77, 82));
        txtLog.setRows(5);
        jScrollPane1.setViewportView(txtLog);

        lblTTL.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        lblTTL.setForeground(new java.awt.Color(73, 77, 82));
        lblTTL.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTTL.setText("TTL:");

        txtTTL.setBackground(new java.awt.Color(246, 246, 246));
        txtTTL.setForeground(new java.awt.Color(73, 77, 82));
        txtTTL.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtTTL.setText("60");

        btnStop.setBackground(new java.awt.Color(168, 212, 252));
        btnStop.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        btnStop.setForeground(new java.awt.Color(73, 77, 82));
        btnStop.setText("Stop");
        btnStop.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnStop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStopActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblUser, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(16, 16, 16)
                        .addComponent(txtUser)
                        .addGap(9, 9, 9))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(lblPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPassword)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(lblTTL, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtTTL, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 79, Short.MAX_VALUE)
                        .addComponent(btnStart, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnStop, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblUser))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPassword))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnStart, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblTTL)
                            .addComponent(txtTTL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(btnStop, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );

        lblPassword.getAccessibleContext().setAccessibleName("lblPassword");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStartActionPerformed
        if(txtUser.getText()== null || txtUser.getText().length()<1){
            JOptionPane.showMessageDialog(this, "User is empty.","Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if(txtPassword.getText()== null || txtPassword.getText().length()<1){
            JOptionPane.showMessageDialog(this, "Password is empty.","Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if(txtTTL.getText()== null || txtTTL.getText().length()<1){
            JOptionPane.showMessageDialog(this, "MTU is empty.","Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        int mtu = 0;
        try{ mtu = Integer.parseInt(txtTTL.getText()); }
        catch(NumberFormatException e){
            JOptionPane.showMessageDialog(this,"MTU is not a number.","Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if(mtu ==0){
            JOptionPane.showMessageDialog(this, "MTU cant be 0.","Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        this.data = new Data(txtUser.getText(), txtPassword.getText(), mtu);
        try { Data.save(this.data); }
        catch (IOException ex) { ex.printStackTrace(); }
        this.update=new UpdateThread(data, txtLog);
        this.update.Start();
        this.btnStart.setEnabled(false);
    }//GEN-LAST:event_btnStartActionPerformed

    private void btnStopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStopActionPerformed
        if(this.update==null){return;}
        this.update.Stop(); 
        this.txtLog.setText("");
        this.btnStart.setEnabled(true);
    }//GEN-LAST:event_btnStopActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DynuClientWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DynuClientWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DynuClientWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DynuClientWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DynuClientWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnStart;
    private javax.swing.JButton btnStop;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblTTL;
    private javax.swing.JLabel lblUser;
    private javax.swing.JTextArea txtLog;
    private javax.swing.JTextField txtPassword;
    private javax.swing.JTextField txtTTL;
    private javax.swing.JTextField txtUser;
    // End of variables declaration//GEN-END:variables
}
